import { useState } from "react";
import { Panel } from "../../components/ui/Panel.jsx";
import { D, alpha } from "../../theme/tokens.js";


export function TermsPanel({onClose}){
  const [expandedSection,setExpandedSection]=useState(null);

  const sections=[
    {n:"1",t:"Introduction",b:"Welcome to PickleLive Pro, a mobile-first pickleball tournament management, matchmaking, club organization, and sports rating platform developed and operated by PickleLive Technologies. These Terms constitute a legally binding contract governing your access to and use of the Application. By downloading, installing, accessing, or using PickleLive Pro, you acknowledge that you have read, understood, and agree to be legally bound by these Terms."},
    {n:"2",t:"Definitions",b:"Key terms used throughout this Agreement: 'Application' means PickleLive Pro. 'Company' means PickleLive Technologies. 'User' means any individual who uses the Application. 'Account' means your registered user profile. 'Content' means any data, text, images or material submitted through the Application. 'Match' means any pickleball game recorded through the Application. 'Rating' means any sports performance rating assigned to a User. 'Club' means any pickleball club or game session created through the Application. 'Third-Party Services' means external platforms and APIs integrated into the Application."},
    {n:"3",t:"Acceptance of Terms",b:"By accessing or using PickleLive Pro, you expressly agree to be bound by these Terms, our Privacy Policy, and any additional guidelines applicable to specific features. Your continued use following updates to these Terms constitutes your acceptance of those changes. These Terms are effective as of the date you first access or use the Application."},
    {n:"4",t:"Eligibility",b:"To use PickleLive Pro you must: be at least 13 years of age (with parental consent if under 18); be at least 18 years of age to make in-app purchases; have legal capacity to enter into a binding contract; not be subject to any ban previously imposed by the Company; and provide accurate, current, and complete information during registration."},
    {n:"5",t:"User Accounts",b:"Account creation requires a full name, unique username, email, and password. You must provide accurate, truthful information. Each person may maintain only one active Account. Accounts are personal and non-transferable. Administrator Accounts are strictly reserved for authorized Company personnel."},
    {n:"6",t:"Registration Requirements",b:"During registration you must provide: Full legal name; Valid email address; Secure password (minimum 6 characters); Email verification code; Age; Sex; Physical address; Country of residence; Phone number with international country code; Agreement to Terms and Privacy Policy. All information must be accurate and complete. The Company is not responsible for consequences arising from inaccurate information provided by you."},
    {n:"7",t:"Account Security",b:"You are solely responsible for maintaining the confidentiality and security of your Account credentials. You agree to: choose a strong unique password; not share credentials with any third party; log out of shared devices; immediately notify us of any unauthorized access. The Company will never ask for your password. You are responsible for all activities that occur under your Account."},
    {n:"8",t:"User Responsibilities",b:"As a User you agree to: use the Application solely for its intended purpose; comply with all applicable laws; respect the rights and privacy of other Users; enter match results honestly; promptly report bugs or security vulnerabilities; maintain confidentiality of other Users' information; comply with Club rules; and accept responsibility for all Content you submit."},
    {n:"9",t:"Acceptable Use Policy",b:"PickleLive Pro is designed exclusively for lawful pickleball sports management. Acceptable uses include: creating and managing player profiles; recording match results; creating and joining clubs and game sessions; viewing ratings and leaderboards; managing social connections; sharing live match links; importing player rosters; and tournament organization."},
    {n:"10",t:"Prohibited Activities",b:"Strictly prohibited activities include: falsifying match results; creating fake accounts; impersonating others; rating manipulation through collusion or match-fixing; reverse engineering the Application; using automated bots or scrapers; bypassing security features; injecting malware; uploading defamatory or hateful content; infringing intellectual property; distributing spam; violating privacy rights; reselling Application access without authorization; and any unlawful activity."},
    {n:"11",t:"User Content",b:"All User Content must comply with these Terms and applicable laws. You are solely responsible for the accuracy, legality, and appropriateness of all Content you submit. By submitting User Content, you grant the Company a non-exclusive, worldwide, royalty-free license to use, reproduce, modify, distribute, display, and perform your Content in connection with operating and improving the Application. You are not entitled to compensation for User Content."},
    {n:"12",t:"Content Ownership & Intellectual Property",b:"All content created by the Company, including design, graphics, logos, trademarks, text, and functionality, is the exclusive property of PickleLive Technologies. You retain ownership of original User Content you create, subject to the license granted above. The Company retains all rights to aggregated, de-identified data. All intellectual property rights in the Application are owned by or licensed to PickleLive Technologies. Unauthorized use of our intellectual property is strictly prohibited."},
    {n:"13",t:"Software License",b:"Subject to your compliance with these Terms, you are granted a limited, non-exclusive, non-transferable, revocable, personal license to download, install, and use the Application solely for personal, non-commercial pickleball management purposes. The software is licensed, not sold. You may not copy, modify, distribute, sell, decompile, reverse engineer, or create derivative works based upon the Application."},
    {n:"14",t:"Third-Party Services & APIs",b:"PickleLive Pro integrates with third-party services including mapping services (Google Maps), email platforms, analytics providers, and sports data services. Third-party services are provided under separate terms and privacy policies. The Company does not control and is not responsible for third-party content, privacy practices, or API accuracy. API data is provided 'as is' and the Company accepts no liability for errors, delays, or inaccuracies in third-party API data."},
    {n:"15",t:"Payment Terms",b:"Certain features require payment including premium subscriptions, club entry fees, and in-app purchases. All prices are listed in Philippine Peso (PHP) unless otherwise specified. You must provide valid payment information. All transactions are subject to applicable taxes. Subscriptions auto-renew unless cancelled before the renewal date through your app store subscription settings. Cancellations take effect at the end of the current billing period."},
    {n:"16",t:"Refund Policy",b:"All purchases are generally non-refundable except as required by applicable law or platform policies. Refund requests for purchases through the Google Play Store or Apple App Store must be directed to those platforms in accordance with their own refund policies. The Company may, at its sole discretion, issue credits in exceptional circumstances. Unused subscription time is not refundable upon cancellation unless required by law."},
    {n:"17",t:"Data Collection & Privacy",b:"PickleLive Pro collects personal and non-personal data necessary to provide and improve our Services, in compliance with the Philippine Data Privacy Act of 2012 (RA 10173), GDPR principles, and CCPA where applicable. Data collected includes registration information, match and game data, club information, device identifiers, and usage data. You have the right to access, correct, delete, or restrict processing of your Personal Data. Full details are in our Privacy Policy."},
    {n:"18",t:"Sports Rating Disclaimer",b:"Sports performance ratings within PickleLive Pro are calculated based on match data entered by Users and are provided for recreational and organizational purposes only. Ratings are not guaranteed to be accurate, comprehensive, or comparable to official ratings from any third-party organization including DUPR. The Company is not affiliated with, endorsed by, or partnered with DUPR or any official rating organization unless explicitly stated. Ratings should not be used as the sole basis for competitive selection, professional assessment, or financial decisions."},
    {n:"19",t:"AI Features Disclaimer",b:"PickleLive Pro may incorporate artificial intelligence or machine learning features including matchmaking suggestions, player recommendations, and performance analytics. All AI-generated outputs are provided for informational and entertainment purposes only. They do not constitute professional sports coaching, medical, financial, or legal advice. The Company makes no warranties regarding the accuracy or reliability of AI-generated content. You use AI features at your own discretion and risk."},
    {n:"20",t:"Disclaimer of Warranties",b:"THE APPLICATION AND ALL SERVICES ARE PROVIDED 'AS IS' AND 'AS AVAILABLE' WITHOUT WARRANTY OF ANY KIND. THE COMPANY EXPRESSLY DISCLAIMS ALL WARRANTIES INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. THE COMPANY DOES NOT WARRANT THAT THE APPLICATION WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS."},
    {n:"21",t:"Limitation of Liability",b:"To the maximum extent permitted by law, PickleLive Technologies shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Application. The Company's aggregate liability shall not exceed the greater of: the total amount paid by you in the twelve months preceding the event; or PHP 1,000.00. This limitation applies regardless of the form of action and whether the Company has been advised of the possibility of such damages."},
    {n:"22",t:"Indemnification",b:"You agree to defend, indemnify, and hold harmless PickleLive Technologies and its affiliates, directors, officers, and employees from and against any claims, liabilities, damages, losses, costs, and fees (including attorneys' fees) arising from: your use of the Application; your violation of these Terms; your violation of any applicable law or third-party rights; any User Content submitted by you; or any fraud or negligence by you."},
    {n:"23",t:"Governing Law & Dispute Resolution",b:"These Terms are governed by the laws of the Republic of the Philippines. Disputes shall first be attempted to be resolved through good-faith negotiation by contacting support@picklelive.com. If unresolved within 60 days, disputes may be submitted to binding arbitration administered by the Philippine Dispute Resolution Center, Inc. (PDRCI) in Metro Manila. The arbitrator's decision shall be final and binding."},
    {n:"24",t:"Account Termination",b:"The Company may terminate your Account at any time for material breach of these Terms, fraudulent activity, non-payment, or legal requirements. You may delete your Account at any time through the Application settings. Upon termination, your license ceases immediately, your data may be deleted or anonymized, and all outstanding obligations remain due. Provisions regarding intellectual property, disclaimers, indemnification, and limitation of liability survive termination."},
    {n:"25",t:"Children's Privacy (COPPA)",b:"PickleLive Pro is not directed to children under the age of 13. The Company does not knowingly collect Personal Data from children under 13. Users between 13 and 17 must have verifiable parental consent. If you believe your child has provided Personal Data to the Application, contact us at support@picklelive.com immediately and we will delete the information promptly."},
    {n:"26",t:"Community Guidelines",b:"All Users must: treat all players and administrators with respect; not engage in harassment, bullying, or intimidation; enter match results honestly; not share offensive, hateful, or discriminatory content; support fair play and sportsmanship; and report violations promptly. Violations may result in content removal, temporary suspension, or permanent Account termination."},
    {n:"27",t:"Copyright & IP Complaint Procedure",b:"To report copyright infringement, submit a written notice to support@picklelive.com including: identification of the copyrighted work; location of the allegedly infringing material; your contact information; a statement of good faith belief; a statement of accuracy under penalty of perjury; and your electronic or physical signature. Repeat infringers will have their accounts terminated."},
    {n:"28",t:"App Store Compliance",b:"PickleLive Pro complies with Google Play Developer Program Policies and Apple App Store Review Guidelines. For iOS purchases, Apple is not a party to these Terms and has no support obligations. Auto-renewal subscriptions are managed through your device's app store subscription settings. Export compliance: you represent that you are not located in an embargoed country or listed on any restricted persons list."},
    {n:"29",t:"Electronic Communications & Digital Consent",b:"By using PickleLive Pro, you consent to receive electronic communications. All electronic agreements, notices, and communications satisfy legal requirements for written communications under Philippine law and the Electronic Commerce Act of 2000 (RA 8792). Your act of clicking 'I Agree' constitutes your digital signature with the same legal effect as a handwritten signature."},
    {n:"30",t:"Changes to Terms & Contact Information",b:"The Company reserves the right to modify these Terms at any time. Material changes will be notified via in-app notice, email, or push notification, becoming effective 14 days after notification. Continued use constitutes acceptance. For questions or legal notices, contact: support@picklelive.com | www.picklelive.com | PickleLive Technologies, Philippines. Support Hours: Monday–Friday, 9:00 AM – 6:00 PM PST."},
  ];

  return(
    <Panel title="Terms & Conditions" sub="PickleLive Pro · Effective June 28, 2026" onClose={onClose}>
        {/* Header Card */}
        <div style={{background:D.accentBg,border:`1px solid ${alpha(D.accent,15)}`,borderRadius:"var(--r-lg)",padding:"16px",marginBottom:16,textAlign:"center"}}>
          <div style={{fontSize:28,marginBottom:8}}>📋</div>
          <div style={{fontWeight:900,fontSize:16,color:D.textPrimary,marginBottom:4}}>PickleLive Pro</div>
          <div style={{fontSize:11,color:D.textSecondary,marginBottom:4}}>Terms and Conditions</div>
          <div style={{display:"flex",justifyContent:"center",gap:12,flexWrap:"wrap"}}>
            <span style={{fontSize:10,background:D.accentBg,border:`1px solid ${alpha(D.accent,25)}`,borderRadius:5,padding:"2px 8px",color:D.accent}}>Effective: Jun 28, 2026</span>
            <span style={{fontSize:10,background:D.greenBg,border:`1px solid ${alpha(D.green,25)}`,borderRadius:5,padding:"2px 8px",color:D.green}}>{sections.length} Sections</span>
            <span style={{fontSize:10,background:D.amberBg,border:`1px solid ${alpha(D.amber,25)}`,borderRadius:5,padding:"2px 8px",color:D.amber}}>Governing Law: Philippines</span>
          </div>
        </div>

        <div style={{fontSize:11,color:D.textSecondary,lineHeight:1.7,marginBottom:14,padding:"10px 12px",background:D.cardEl,borderRadius:"var(--r-md)",border:`1px solid ${D.border}`}}>
          By using PickleLive Pro, you agree to these Terms and Conditions in their entirety. Tap any section below to read the full text. These Terms comply with the Philippine Data Privacy Act (RA 10173), Google Play Policies, and Apple App Store Guidelines.
        </div>

        {sections.map((s,i)=>(
          <div key={s.n} style={{background:D.cardEl,border:`1px solid ${D.border}`,borderRadius:"var(--r-md)",marginBottom:6,overflow:"hidden"}}>
            <button onClick={()=>setExpandedSection(expandedSection===i?null:i)}
              style={{width:"100%",padding:"13px 14px",background:"transparent",border:"none",display:"flex",justifyContent:"space-between",alignItems:"center",cursor:"pointer",textAlign:"left"}}>
              <div style={{display:"flex",alignItems:"center",gap:10,flex:1,minWidth:0}}>
                <span style={{width:26,height:26,borderRadius:7,background:alpha(D.accent,9),border:`1px solid ${alpha(D.accent,25)}`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:9,fontWeight:900,color:D.accent,flexShrink:0}}>{s.n}</span>
                <span style={{fontSize:12,fontWeight:700,color:D.textPrimary,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{s.t}</span>
              </div>
              <span style={{color:D.accent,fontSize:16,flexShrink:0,marginLeft:8,transition:"transform .2s",transform:expandedSection===i?"rotate(45deg)":"none"}}>+</span>
            </button>
            {expandedSection===i&&(
              <div style={{padding:"0 14px 14px",fontSize:12,color:D.textSecondary,lineHeight:1.8,borderTop:`1px solid ${D.border}`,paddingTop:12}}>
                {s.b}
              </div>
            )}
          </div>
        ))}

        {/* Footer */}
        <div style={{marginTop:16,padding:"14px",background:D.cardEl,border:`1px solid ${D.border}`,borderRadius:"var(--r-md)",textAlign:"center"}}>
          <div style={{fontSize:11,color:D.textSecondary,lineHeight:1.7}}>
            Questions? Contact us at{" "}
            <span style={{color:D.accent,fontWeight:600}}>support@picklelive.com</span>
          </div>
          <div style={{fontSize:10,color:D.textMuted,marginTop:6}}>© 2026 PickleLive Technologies. All rights reserved.</div>
        </div>
    </Panel>
  );
}
